# Generated by Django 4.2.13 on 2024-06-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_subjectnotes_chapterquiz_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchapterquizanswer',
            name='selected_answer',
            field=models.CharField(max_length=1,null=True,blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='choice_a',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='choice_b',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='choice_c',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='choice_d',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('Vels University', 'Vels University'), ('Crescent', 'Crescent'), ('Jamal Mohamad', 'Jamal Mohamad'), ('Malla Reddy', 'Malla Reddy'), ('MHCockpit', 'MHCockpit')], max_length=100),
        ),
    ]
