# Generated by Django 4.2.13 on 2024-07-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chapterquiz_explanation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectProgress',
        ),
    ]
